### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by eizoxx** [shadowcz007/comfyui-liveportrait#24]
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\main.py", line 80, in <module>
    import execution
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Getting this error, when I try to install and restart LivePortrait

**Comment by eizoxx** [comment]
I got it to work!!!
First I figured out that it had to something with **(IMPORT FAILED) comfyui-liveportrait** in the ComfyUI Custom Node Manager
I simply followed this guide:
https://www.reddit.com/r/comfyui/comments/1b4u63e/import_failed/
I simplified it a bit with ChatGPT, but I followed **leftclot's** workaround
